---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-test-openstack-org-v1beta1-ansibletest
  failurePolicy: Fail
  name: mansibletest.kb.io
  rules:
  - apiGroups:
    - test.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ansibletests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-test-openstack-org-v1beta1-horizontest
  failurePolicy: Fail
  name: mhorizontest.kb.io
  rules:
  - apiGroups:
    - test.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - horizontests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-test-openstack-org-v1beta1-tempest
  failurePolicy: Fail
  name: mtempest.kb.io
  rules:
  - apiGroups:
    - test.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tempests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-test-openstack-org-v1beta1-tobiko
  failurePolicy: Fail
  name: mtobiko.kb.io
  rules:
  - apiGroups:
    - test.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tobikoes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-test-openstack-org-v1beta1-ansibletest
  failurePolicy: Fail
  name: vansibletest.kb.io
  rules:
  - apiGroups:
    - test.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ansibletests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-test-openstack-org-v1beta1-horizontest
  failurePolicy: Fail
  name: vhorizontest.kb.io
  rules:
  - apiGroups:
    - test.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - horizontests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-test-openstack-org-v1beta1-tempest
  failurePolicy: Fail
  name: vtempest.kb.io
  rules:
  - apiGroups:
    - test.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tempests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-test-openstack-org-v1beta1-tobiko
  failurePolicy: Fail
  name: vtobiko.kb.io
  rules:
  - apiGroups:
    - test.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tobikoes
  sideEffects: None
