# permissions for end users to view tobikoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tobiko-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-operator
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: tobiko-viewer-role
rules:
- apiGroups:
  - test.openstack.org
  resources:
  - tobikoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.openstack.org
  resources:
  - tobikoes/status
  verbs:
  - get
