# permissions for end users to edit tobikoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tobiko-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-operator
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: tobiko-editor-role
rules:
- apiGroups:
  - test.openstack.org
  resources:
  - tobikoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.openstack.org
  resources:
  - tobikoes/status
  verbs:
  - get
