---
apiVersion: v1
kind: Pod
metadata:
  name: test-operator-logs-pod
  namespace: "openstack"
spec:
  containers:
    - name: test-operator-logs-container
      image: quay.io/openshifttest/busybox
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      volumeMounts:
        - name: logs-volume
          mountPath: /mnt
  volumes:
    - name: logs-volume
      persistentVolumeClaim:
        claimName: test-operator-logs
