apiVersion: test.openstack.org/v1beta1
kind: Tempest
metadata:
  name: tempest-tests
  namespace: openstack
spec:
  containerImage: quay.io/podified-antelope-centos9/openstack-tempest:current-podified
  secret: tempest-secret
