clouds:
  default:
    auth:
      auth_url: {{ .KeystoneApiEndpoint }}
      project_name: admin
      username: admin
      user_domain_name: Default
      project_domain_name: Default
      password: {{ .OpenStackAdminPassword }}
    region_name: regionOne
